#pragma once

#define CARDANO_BLST_P1_SIZE 144
#define CARDANO_BLST_P2_SIZE 288
#define CARDANO_BLST_AFFINE1_SIZE 96
#define CARDANO_BLST_AFFINE2_SIZE 192
#define CARDANO_BLST_SCALAR_SIZE 32
#define CARDANO_BLST_FR_SIZE 32
#define CARDANO_BLST_FP12_SIZE 576
