# a non-flake nix compat wrapper using https://github.com/edolstra/flake-compat
# DO NOT EDIT THIS FILE
__trace
     ''************************************************************************************
        Hi there! This project has been moved to nix flakes. You are using the default.nix
        compatibility layer. Please consider using flake commands like `nix build .#...`,
        `nix repl` with `:lf .` and similar instead.
       ************************************************************************************
''
(import
  (
    let lock = builtins.fromJSON (builtins.readFile ./flake.lock); in
    fetchTarball {
      url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
      sha256 = lock.nodes.flake-compat.locked.narHash;
    }
  )
  { src = ./.; }
).defaultNix
