resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/0c5b0a6619fadf22f4d62a12154e181a6d035c1c/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

ghc-options:
  binary:                 -Wall
  binary-test:            -Wall
  cardano-crypto-class:   -Wall
  slotting:               -Wall

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 0c5b0a6619fadf22f4d62a12154e181a6d035c1c
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
