resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/cb54482c7e3d45f6c1aac490dc937ed835de0333/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: cb54482c7e3d45f6c1aac490dc937ed835de0333
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
