resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/91f357abae16099858193b999807323ca9a7c63c/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

ghc-options:
  binary:                 -Wall
  binary-test:            -Wall
  cardano-crypto-class:   -Wall
  slotting:               -Wall

allow-newer: true

extra-deps:
  - quiet-0.2

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 91f357abae16099858193b999807323ca9a7c63c
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
