/* This is an automatically generated file */

#ifndef quirks_H
#ifndef NO_QUIRKS

#define argon2_ctx sodium_argon2_ctx
#define argon2_decode_string sodium_argon2_decode_string
#define argon2_encode_string sodium_argon2_encode_string
#define argon2_fill_memory_blocks sodium_argon2_fill_memory_blocks
#define argon2_fill_segment_avx2 sodium_argon2_fill_segment_avx2
#define argon2_fill_segment_avx512f sodium_argon2_fill_segment_avx512f
#define argon2_fill_segment_ref sodium_argon2_fill_segment_ref
#define argon2_fill_segment_ssse3 sodium_argon2_fill_segment_ssse3
#define argon2_finalize sodium_argon2_finalize
#define argon2_hash sodium_argon2_hash
#define argon2_initialize sodium_argon2_initialize
#define argon2_validate_inputs sodium_argon2_validate_inputs
#define argon2_verify sodium_argon2_verify
#define argon2i_hash_encoded sodium_argon2i_hash_encoded
#define argon2i_hash_raw sodium_argon2i_hash_raw
#define argon2i_verify sodium_argon2i_verify
#define argon2id_hash_encoded sodium_argon2id_hash_encoded
#define argon2id_hash_raw sodium_argon2id_hash_raw
#define argon2id_verify sodium_argon2id_verify
#define blake2b sodium_blake2b
#define blake2b_compress_avx2 sodium_blake2b_compress_avx2
#define blake2b_compress_ref sodium_blake2b_compress_ref
#define blake2b_compress_sse41 sodium_blake2b_compress_sse41
#define blake2b_compress_ssse3 sodium_blake2b_compress_ssse3
#define blake2b_final sodium_blake2b_final
#define blake2b_init sodium_blake2b_init
#define blake2b_init_key sodium_blake2b_init_key
#define blake2b_init_key_salt_personal sodium_blake2b_init_key_salt_personal
#define blake2b_init_param sodium_blake2b_init_param
#define blake2b_init_salt_personal sodium_blake2b_init_salt_personal
#define blake2b_long sodium_blake2b_long
#define blake2b_pick_best_implementation sodium_blake2b_pick_best_implementation
#define blake2b_salt_personal sodium_blake2b_salt_personal
#define blake2b_update sodium_blake2b_update
#define escrypt_PBKDF2_SHA256 sodium_escrypt_PBKDF2_SHA256
#define escrypt_alloc_region sodium_escrypt_alloc_region
#define escrypt_free_local sodium_escrypt_free_local
#define escrypt_free_region sodium_escrypt_free_region
#define escrypt_gensalt_r sodium_escrypt_gensalt_r
#define escrypt_init_local sodium_escrypt_init_local
#define escrypt_kdf_nosse sodium_escrypt_kdf_nosse
#define escrypt_kdf_sse sodium_escrypt_kdf_sse
#define escrypt_parse_setting sodium_escrypt_parse_setting
#define escrypt_r sodium_escrypt_r
#define fe25519_frombytes sodium_fe25519_frombytes
#define fe25519_invert sodium_fe25519_invert
#define fe25519_tobytes sodium_fe25519_tobytes
#define ge25519_add sodium_ge25519_add
#define ge25519_double_scalarmult_vartime sodium_ge25519_double_scalarmult_vartime
#define ge25519_from_hash sodium_ge25519_from_hash
#define ge25519_from_uniform sodium_ge25519_from_uniform
#define ge25519_frombytes sodium_ge25519_frombytes
#define ge25519_frombytes_negate_vartime sodium_ge25519_frombytes_negate_vartime
#define ge25519_has_small_order sodium_ge25519_has_small_order
#define ge25519_is_canonical sodium_ge25519_is_canonical
#define ge25519_is_on_curve sodium_ge25519_is_on_curve
#define ge25519_is_on_main_subgroup sodium_ge25519_is_on_main_subgroup
#define ge25519_p1p1_to_p2 sodium_ge25519_p1p1_to_p2
#define ge25519_p1p1_to_p3 sodium_ge25519_p1p1_to_p3
#define ge25519_p3_to_cached sodium_ge25519_p3_to_cached
#define ge25519_p3_tobytes sodium_ge25519_p3_tobytes
#define ge25519_scalarmult sodium_ge25519_scalarmult
#define ge25519_scalarmult_base sodium_ge25519_scalarmult_base
#define ge25519_sub sodium_ge25519_sub
#define ge25519_tobytes sodium_ge25519_tobytes
#define ristretto255_from_hash sodium_ristretto255_from_hash
#define ristretto255_frombytes sodium_ristretto255_frombytes
#define ristretto255_p3_tobytes sodium_ristretto255_p3_tobytes
#define sc25519_invert sodium_sc25519_invert
#define sc25519_is_canonical sodium_sc25519_is_canonical
#define sc25519_mul sodium_sc25519_mul
#define sc25519_muladd sodium_sc25519_muladd
#define sc25519_reduce sodium_sc25519_reduce

#endif
#endif
