[package]
name = "bls12-381-test-vectors"
version = "0.1.0"
edition = "2021"

[dependencies]
bls12_381 = { version = "0.8.0", features = ["default", "experimental"] }
rand_chacha = "0.3.1"
ff = "0.13.0"
group = "0.13.0"
hex = "0.4.3"
blst = "0.3.10"
sha2 = "0.9"
