name:                 base-deriving-via
version:              0.1.0.2
visibility:           public
id:                   base-deriving-via-0.1.0.2-inplace
key:                  base-deriving-via-0.1.0.2-inplace
license:              Apache-2.0
copyright:            IOHK
maintainer:           operations@iohk.io
author:               IOHK
synopsis:             A general hook newtype for use with deriving via
abi:                  inplace
exposed:              True
exposed-modules:
    Data.DerivingVia Data.DerivingVia.GHC.Generics.Monoid
    Data.DerivingVia.GHC.Generics.Semigroup

import-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/base-deriving-via-0.1.0.2/build

library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/base-deriving-via-0.1.0.2/build

dynamic-library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/base-deriving-via-0.1.0.2/build

data-dir:
    /home/runner/work/cardano-base/cardano-base/base-deriving-via/.

hs-libraries:         HSbase-deriving-via-0.1.0.2-inplace
depends:              base-4.16.4.0
haddock-interfaces:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/base-deriving-via-0.1.0.2/doc/html/base-deriving-via/base-deriving-via.haddock

haddock-html:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/base-deriving-via-0.1.0.2/doc/html/base-deriving-via
