name:                 cardano-mempool
version:              0.1.0.0
visibility:           public
id:                   cardano-mempool-0.1.0.0-inplace
key:                  cardano-mempool-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2022 IOHK
maintainer:           operations@iohk.io
author:               IOHK
homepage:             https://github.com/input-output-hk/cardano-base
synopsis:             Short description
description:          Lock-free threadsafe pinned memory pool
category:             Memory
abi:                  inplace
exposed:              True
exposed-modules:      Cardano.Memory.Pool
import-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-mempool-0.1.0.0/build

library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-mempool-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-mempool-0.1.0.0/build

data-dir:
    /home/runner/work/cardano-base/cardano-base/cardano-mempool/.

hs-libraries:         HScardano-mempool-0.1.0.0-inplace
depends:
    base-4.16.4.0 primitive-0.9.0.0-1bBNXP697CR7CDtr2zom3J
    pvar-1.0.0.0-D5GCFixeQ6b5o7Pt09RfeO

haddock-interfaces:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-mempool-0.1.0.0/doc/html/cardano-mempool/cardano-mempool.haddock

haddock-html:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-mempool-0.1.0.0/doc/html/cardano-mempool
