name:                 cardano-binary-test
version:              1.4.0.2
visibility:           public
id:                   cardano-binary-test-1.4.0.2-inplace
key:                  cardano-binary-test-1.4.0.2-inplace
license:              MIT
copyright:            2019-2021 IOHK
maintainer:           operations@iohk.io
author:               IOHK
synopsis:             Test helpers from cardano-binary exposed to other packages
description:          Test helpers from cardano-binary exposed to other packages
category:             Currency
abi:                  inplace
exposed:              True
exposed-modules:
    Test.Cardano.Binary.Failure Test.Cardano.Binary.Helpers
    Test.Cardano.Binary.Helpers.GoldenRoundTrip
    Test.Cardano.Binary.Serialization

import-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-binary-test-1.4.0.2/build

library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-binary-test-1.4.0.2/build

dynamic-library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-binary-test-1.4.0.2/build

data-dir:
    /home/runner/work/cardano-base/cardano-base/cardano-binary/test/.

hs-libraries:         HScardano-binary-test-1.4.0.2-inplace
depends:
    QuickCheck-2.14.3-8eSLWWVDJv1Dhc77HTD7lg base-4.16.4.0
    bytestring-0.11.4.0-20YrNqjxeS9FbmijR89bLb
    cardano-binary-1.7.1.0-inplace
    cardano-prelude-test-0.1.0.2-2aOmzsXNpdJJnwIzjO3u5B
    cborg-0.2.10.0-7AQZ8GjXTLBCamfWKaVYoA
    containers-0.6.5.1-LoBk5T9QwNLBqnqOQVtDCh
    formatting-7.2.0-1wFTofT8lvlHDvvMRE24zm
    hedgehog-1.4-GQbfUXyka75IhNE8YcFcQp
    hspec-2.11.7-7NonQBO7UZOKJwmNMkbuDD
    pretty-show-1.10-DlIgl9l8XETBAoXOtHGDOV
    quickcheck-instances-0.3.30-DfnW6KGTXDMKUCk57nnKpu
    text-1.2.5.0-Ii1ClGOyJQ8AmHgulTPR3f
    time-1.11.1.1-3c78rVb4UjbAw9ujAnKmhM
    vector-0.13.1.0-2olqiNuZ77hIhZlgH4W84M

haddock-interfaces:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-binary-test-1.4.0.2/doc/html/cardano-binary-test/cardano-binary-test.haddock

haddock-html:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/cardano-binary-test-1.4.0.2/doc/html/cardano-binary-test
