name:                 orphans-deriving-via
version:              0.1.0.2
visibility:           public
id:                   orphans-deriving-via-0.1.0.2-inplace
key:                  orphans-deriving-via-0.1.0.2-inplace
license:              Apache-2.0
copyright:            IOHK
maintainer:           operations@iohk.io
author:               IOHK
synopsis:             Orphan instances for the base-deriving-via hooks
abi:                  inplace
exposed:              True
exposed-modules:      Data.DerivingVia.DeepSeq Data.DerivingVia.NoThunks
import-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/orphans-deriving-via-0.1.0.2/build

library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/orphans-deriving-via-0.1.0.2/build

dynamic-library-dirs:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/orphans-deriving-via-0.1.0.2/build

data-dir:
    /home/runner/work/cardano-base/cardano-base/orphans-deriving-via/.

hs-libraries:         HSorphans-deriving-via-0.1.0.2-inplace
depends:
    base-4.16.4.0 base-deriving-via-0.1.0.2-inplace deepseq-1.4.6.1
    nothunks-0.2.1.0-JpteMOXfpzx34LXFyX3W4k

haddock-interfaces:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/orphans-deriving-via-0.1.0.2/doc/html/orphans-deriving-via/orphans-deriving-via.haddock

haddock-html:
    /home/runner/work/cardano-base/cardano-base/dist-newstyle/build/x86_64-linux/ghc-9.2.8/orphans-deriving-via-0.1.0.2/doc/html/orphans-deriving-via
